apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: abcdesktop-ns
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hub.jupyter.org/node-purpose
            operator: In
            values:
            - user
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - sleep
        - infinity
          #      volumeMounts:
          # - mountPath: /mnt
          #name: embl-home
      securityContext:
        runAsGroup: 368
        runAsUser: 24143
      resources:
        limits:
          cpu: 250m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 32Mi


