apiVersion: v1
kind: Pod
metadata:
  name: podapp
  namespace: abcdesktop
spec:
  volumes:
  - name: x11socket
    hostPath:
      # x11 directory location on host 591d3b3a-e390-49c8-9424-695931356085
      path: /var/lib/kubelet/pods/591d3b3a-e390-49c8-9424-695931356085/volumes/kubernetes.io~empty-dir/x11socket
      # this field is optional
      type: Directory
  - name: home
    hostPath:
      # home directory location on host
      path: /nfs/home/yisun
      # this field is optional
      type: Directory
  containers:
  - name: abccontainer
    #    image: ubuntu:20.04
    image: registry.git.embl.de/ysun/abcdesktop-apps/jupyterlab
    command: ["/bin/sleep"]
    args: ["1d"]
    volumeMounts:
    - mountPath: /tmp/.X11-unix
      name: x11socket
    - mountPath: /home/yisun
      name: home
    env:
    - name: XAUTH_KEY
      value: 255e9fd5c9009717407f8c81b435eb

