---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: beegfs-scratch-denbi-pv
  labels:
    capsule.clastix.io/tenant: abcdesktop
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Pi
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: beegfs.csi.netapp.com
    # Replace "localhost" with the IP address or hostname of the BeeGFS management daemon.
    #     # "all" k8s clusters may share access to statically provisioned volumes.
    #         # Ensure that the directory, e.g. "k8s/all/static", exists on BeeGFS.  The driver will not create the directory.
    volumeHandle: beegfs://10.11.12.90/k8s/denbi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beegfs-scratch-denbi-pvc
  namespace: abcdesktop-external-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Pi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: beegfs-scratch-denbi-pv
